"""empty message

Revision ID: ac3d61010e2d
Revises: a76f7d9f2415
Create Date: 2018-06-30 03:27:52.145074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3d61010e2d'
down_revision = 'a76f7d9f2415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mahasiswa', 'nim',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mahasiswa', 'nim',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
